[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Netlify Functions 配置
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Next.js 重定向规则
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {path = ["/api/*"]}

# 保持现有的Next.js路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 环境变量说明（需要在Netlify控制台中设置）
# NEXT_PUBLIC_SUPABASE_URL = "你的Supabase项目URL"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "你的Supabase匿名密钥"
# SUPABASE_SERVICE_ROLE_KEY = "你的Supabase服务角色密钥"（可选）